project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Master Carthagéo"
  google-analytics: "G-Y4HLV126SE"
  favicon: "img/favicon.png"
  twitter-card: true
  site-url: https://carthageo.github.io
  open-graph: 
    locale: fr_FR
    site-name: Master Carthagéo
  page-footer: 
    left: |
      [![](img/logo_Paris1_min.png){fig-alt="Université Paris 1 Panthéon-Sorbonne" height=75px}](https://formations.pantheonsorbonne.fr/fr/catalogue-des-formations/master-M/master-geographie-KBUW66GE//master-parcours-carthageo-KBUW66XE.html)
    center: |
      [![](img/logo_GeoDataParis.jpg){fig-alt="Géodata Paris" height=75px}](https://geodata-paris.fr/fr/formation-initiale/master-2-carthageo)
    right: |
      [![](img/logo_UPC_min.png){fig-alt="Université Paris Cité" height=75px}](https://odf.u-paris.fr/fr/offre-de-formation/master-XB/sciences-humaines-et-sociales-SHS/geographie-amenagement-environnement-et-developpement-K2VO0KVP/master-gaed-parcours-conception-et-construction-de-realisations-geomatiques-carthageo-M34CBYQO.html)
  navbar:
    logo: "img/LOGO_CARTHAGEO.png"
    left:
      - href: index.qmd
        text: "Accueil"
      - href: "" # m1.qmd
        text: "Le Master 1"
      - href: "" # m2.qmd
        text: "Le Master 2"
      - href: admission.qmd
        text: "Admissions"
      - href: "" # apres.qmd
        text: "Après le master"
      - href: "" # about.qmd
        text: "A propos"
      - text: "Réalisations"
        menu:
          - text: "Général"
            href: realisations/realisations.qmd
          - text: "Projet éditorial 2025/2026"
            href: realisations/projet-editorial-2025-2026.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true





